baseURL = "http://example.org/"
languageCode = "en-us"
title = "Story of the day"

themesDir = "themes"
theme = "hugo-winston-theme"

[author]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"

[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true

[[menu.main]]
    name = "Blogs"
    weight = 1
    url  = "/blog/"

